let shoppingCart;
let shoppingCartBtn;
let shoppingCartList;
let shoppingCartInfo;
let cartBtn;
let shoppingCartQuantity;
let quantityBtns;
let quantityValue;
let addToCartBtns;
let allButtons;
let logo;
let previousSections = [];
let popup;
let closePopupBtn;
let orderList;
let ingredientsInputs;
let ingredientPrice;
let dotsBox;
let dots;
let arrowBox;
let newItem;
let currentItem;
let sameItems;
let sameItemsQuantity = 0;
let index = 0;
let countedMinutes, countedSeconds, counting;
let deliveryTimeSpan;
const timesToDeliver = [20, 25, 30, 35, 40, 45, 50];
let exitBtn;